### ISSUE TITLE
tocloft: \cftparskip ignored when using [titles] option

### ISSUE THREAD

**Issue by cousteaulecommandant** [wspr/herries-press#28]
The `\cftparskip` length is ignored when the `[titles]` package option is provided; the ToC uses the regular `\parskip` instead.

Minimal working example:
```LaTeX
\documentclass{article}

%\usepackage{tocloft} % will use \cftparskip in the ToC as expected
\usepackage[titles]{tocloft} % will use \parskip in the ToC instead

\cftparskip=0em
\parskip=1em

\begin{document}

\tableofcontents

\section{Section} blah
    \subsection{Subsection} blah
    \subsection{Subsection} blah
\section{Section} blah
    \subsection{Subsection} blah
    \subsection{Subsection} blah
        \subsubsection{Subsubsection} blah
        \subsubsection{Subsubsection} blah
        \subsubsection{Subsubsection} blah
    \subsection{Subsection} blah
\section{Section} blah
    \subsection{Subsection} blah
    \subsection{Subsection} blah

\end{document}
```

**Comment by wspr** [comment]
Thanks for the writing — unfortunately I can’t look into this in the near term but will address next time I’m looking into the package code.

**Comment by cousteaulecommandant** [comment]
For now, this **workaround** seems to work:
```LaTeX
\makeatletter
\let\OLD@starttoc=\@starttoc
\renewcommand{\@starttoc}[1]{%
    \begingroup%
        \parskip=\cftparskip%
        \OLD@starttoc{#1}%
    \endgroup%
}
\makeatother
```
(so if someone else is having this issue they can add this after the `\usepackage[titles]{tocloft}` invocation.)

After inspecting the source code of the package, it seems that the problem is that the `\parskip=\cftparskip` assignment is done inside the `\tableofcontents` et al. commands, but these commands are only redefined when the `[titles]` option is not provided.

(If this workaround looks good enough, it could be added to the package, replacing the `\parskip\cftparskip` lines removed.)

**Comment by wspr** [comment]
Thanks for the patch, that is helpful! Without diving into the details further I wouldn’t want to comment on the best way to integrate your workaround into the main package code...

**Comment by wspr** [comment]
Sorry it has taken me so long to look at this. I'm afraid I don't understand your use case — in the documentation it states:

```
% The \Lopt{titles} option causes
% the titles of the ToC, LoF, and LoT lists to be typeset using the
% default \LaTeX{} methods. This can be useful, for example, when the
% \Lpack{tocloft} and \Lpack{fncychap} packages are used together and
% the `fancy' chapter styles should be used for the ToC, etc., titles.
```

So I think the behaviour you're tried to change is intentional.

**Comment by wspr** [comment]
Oops, I was reading too quickly — ignore my comment above.

**Comment by cousteaulecommandant** [comment]
The documentation suggests that the `[titles]` option only affects the **title** of the ToC (i.e. the ***Table of contents*** line); my issue was about the formatting of the ToC **content**, not the title (the lines below the title, e.g. *1. Introduction, 2. Background...*).

(PS: I had this issue nearly 2 years ago so I don't quite remember the details)

**Comment by wspr** [comment]
Yep, sorry I misunderstood originally when I first looked into it. Sorry for the confusion! All fixed in the latest release :-)

**Comment by kleiba** [comment]
Sorry, but where can the updates be found? I don't see any recent pushes. :(
