### ISSUE TITLE
tocloft issues a warning and renounces adding `\cfttocprehook` etc... to `\@starttoc` when parskip is loaded before it

### ISSUE THREAD

**Issue by jfbu** [wspr/herries-press#45]
```latex
\documentclass{book}
\usepackage{parskip}

%\makeatletter
%\show\@starttoc

\usepackage{tocloft}
\begin{document}
\tableofcontents
\section{foo}
\end{document}
```
gives

```
Package tocloft Warning: \@starttoc has already been redefined; tocloft bailing
 out. on input line 1156.
```

It has been reported [already on tex.sx](https://tex.stackexchange.com/q/395779) some years ago. I observed it only today with a class loading `parskip` automatically.

The message is emitted at end of `tocloft.sty` and some functionality is in place only the hooks are not installed. So the message is a bit frightening and should perhaps read `"`\cfttocprehook` et al. not installed"` in place of `"bailing out"`.

**Comment by kberry** [comment]
Thanks for the report. I changed the warning message as you suggested, so closing. Maybe someday we can make a new release ...

**Comment by kberry** [comment]
perhaps read `"`\cfttocprehook` et al. not installed"` in place of
    `"bailing out"`.

Just based on what you wrote here, sounds sensible to me, FWIW.

It would be good to push out a new tocloft, somehow ... --thanks, karl.
